---
output: html_document
---

```{r include=FALSE, warning=FALSE}
print("Buyer Backlog R Scipt")
library(lubridate)
source("./data_import.r")
source("./buyer-backlogs.r")
source("./buyer-backlogs-90dayplus.r")
source("./buyer-backlogs-amounts.r")
source("./approver-backlogs.r")

source("./mongo-time_machine.r")
#source("./buyer-hist.r")
```
# Buyer Backlog Report of `r data_date`

### All Reqs

```{r echo=FALSE, warning=FALSE, fig.align='center', out.width="100%", out.height="400px"}
backlog_plot_ninv <- backlog_plot %>% 
  filter(Category == "NINV") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          width = "20px",
          legendgroup = ~Type) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')

backlog_plot_se <- backlog_plot %>% 
  filter(Category == "SE") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          legendgroup = ~Type, 
          width = "20px",
          showlegend = F) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')

backlog_plot_inv <- backlog_plot %>% 
  filter(Category == "INV") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          legendgroup = ~Type, 
          width = "20px",
          showlegend = F) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')

subplot(backlog_plot_ninv, backlog_plot_se, backlog_plot_inv, nrows = 3, margin = .03, shareX = TRUE)
```

### Reqs Over 90 Days 

```{r echo=FALSE, out.width="100%", out.height="400px"}

backlog_plot_90dayplus_ninv <- backlog_plot_90dayplus %>% 
  filter(Category == "NINV") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          width = "20px",
          legendgroup = ~Type) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')

backlog_plot_90dayplus_se <- backlog_plot_90dayplus %>% 
  filter(Category == "SE") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          width = "20px",
          legendgroup = ~Type,
          showlegend = F) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')

backlog_plot_90dayplus_inv <- backlog_plot_90dayplus %>% 
  filter(Category == "INV") %>% 
  plot_ly() %>% 
  add_bars(y = ~Buyer,
          x = ~Count,
          color = ~Type,
          type = "bar", 
          colors = c("#99D594","#FFFFBF","#FC8D59"),
          width = "20px",
          legendgroup = ~Type,
          showlegend = F) %>% 
  layout(yaxis = list(autorange = "reversed"), barmode = 'stack')


subplot(backlog_plot_90dayplus_ninv, backlog_plot_90dayplus_se, backlog_plot_90dayplus_inv, nrows = 3, margin = .03, shareX = TRUE)

```

## PP's Approval Worklist

```{r echo=FALSE}
kable(approval_kable) %>% 
  kable_styling() %>% 
  add_header_above(c("Grouping By Age (Days)" = 4, "Grouping By Dollar Amount" = 4, " " = 1)) %>% 
  column_spec(9, bold = TRUE) %>% 
  column_spec(c(4), border_right = TRUE, include_thead = TRUE)
```

<P style="page-break-before: always">

### PP's Worklist Details (`r approval_detail_count`)

*Omitted `r (approval_total_count - approval_detail_count)` entries less than $50,000.*


```{r echo=FALSE}
kable(approval_detail_table)%>% 
  kable_styling() %>% 
  add_header_above(c(" " = 1, "Worklist Data" = 3,"Req Details" = 2))
```
<P style="page-break-before: always">

## All Backlog, By Req Age
```{r echo=FALSE}
# This vector holds the buyer counts for this kable, in "NI, SE, INV" order, then add 1 for subtotal line.
# group_rows uses the vector as is for each group.
# row_spec uses cumsum of this value to get the index of last lines of each category
# The index of final Sum row is the sum of the row #s + 1. 
backlog_age_row_num_vec <- as_vector(backlog_age_kable_col_count[[2]]) + 1
kable(backlog_kable) %>% 
  kable_styling() %>% 
  add_header_above(c(" " = 1, "Actionable" = 4, "On Hold" = 1, "Out-to-Bid" = 1, " " = 1)) %>% 
  group_rows(index = c("Non-Inventory" = backlog_age_row_num_vec[1], 
                       "Sourcing Exec." = backlog_age_row_num_vec[2], 
                       "Inventory" = backlog_age_row_num_vec[3],
                       "Total" = 1)) %>% 
  row_spec(cumsum(backlog_age_row_num_vec), italic = TRUE, background = "#EEEEEE") %>% 
  row_spec(sum(backlog_age_row_num_vec) + 1, bold = TRUE)
```
<P style="page-break-before: always">

## Backlog older than 90 days, By Req Amount

```{r echo=FALSE}
backlog_amt_row_num_vec <- as_vector(backlog_amt_kable_col_count[[2]]) + 1
kable(backlog_amount_kable) %>% 
  kable_styling() %>% 
  add_header_above(c(" " = 1, "Actionable" = 3, "On Hold" = 1, "Out-to-Bid" = 1, " " = 1)) %>% 
  group_rows(index = c("Non-Inventory" = backlog_amt_row_num_vec[1], 
                       "Sourcing Exec." = backlog_amt_row_num_vec[2], 
                       "Inventory" = backlog_amt_row_num_vec[3], 
                       "Total" = 1)) %>% 
  row_spec(cumsum(backlog_amt_row_num_vec), italic = TRUE, background = "#EEEEEE") %>% 
  row_spec(sum(backlog_amt_row_num_vec) + 1, bold = TRUE)
```

Using data obtained at `r data_date`. Code version `r code_version`.
