#!/bin/bash

# data_run.sh
# Created by MG
# Import and Execute R script for refreshing buyer backlog report

cd /home/ubuntu/Projects/buyer-backlogs/

echo "# data_import.r" > ./data_import.r
echo "# Generated by data_run.sh" >> ./data_import.r
echo "# Gather variables for data import in one place" >> ./data_import.r

echo "backlog_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/$1/BACKLOG-$1.xlsx'" >> ./data_import.r
echo "approver_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/$1/APPROVER-BACKLOG-$1.xlsx'" >> ./data_import.r

echo "data_date <- ymd( '$(date +%Y-%m-%d)')" >> ./data_import.r

R -f ./main.r

exit 0

