# data_import.r
# Generated by data_run.sh
# Gather variables for data import in one place
backlog_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/09192018-1319/BACKLOG-09192018-1319.xlsx'
approver_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/09192018-1319/APPROVER-BACKLOG-09192018-1319.xlsx'
data_date <- now('America/New_York')
