# data_import.r
# Generated by data_run.sh
# Gather variables for data import in one place
backlog_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/09142018-1419/BACKLOG-09142018-1419.xlsx'
approver_data_path <- '/home/ubuntu/Projects/buyer-backlogs/data/ductpipe/09142018-1419/APPROVER-BACKLOG-09142018-1419.xlsx'
data_date <- ymd( '2018-09-14')
